### PR TITLE
Add type support for array content

### PR DESCRIPTION
**Pull request by tnfAngel**
[Add optional type support for array content](https://github.com/crimson-med/array-limited/commit/b140b3751cc844e241fc9c2712db52cdf6cfd253)

### CODE REVIEW

**Comment by crimson-med** [comment]
will review and merge this and deploy later today!

**Comment by tnfAngel** [comment]
> 

Awesome! Thanks

**Comment by tnfAngel** [comment]
Hello 👋, any updates on this?

**Comment by crimson-med** [comment]
@tnfAngel sorry got pretty busy with work! will be merged tonight (SG time)

**Comment by crimson-med** [comment]
Merged! I'll deploy the update to npm later

**Comment by crimson-med** [comment]
@tnfAngel deployed on npm under 0.0.7

**Comment by tnfAngel** [comment]
Ty!

**Pull request merged**
